### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by badiskerd** [DexSniping/DexSniping-BSC-ERC20-Telegram-Alerts#1]
Hey bro! Nice work, I was asking if you can give me your telegram handle as i want to hire you for a task, thanks!

**Comment by hg-gong** [comment]
hi

I walk through the code and I found the swapper 0xaAA9c55FF5ce8e6431d84BE3cf9d0Ba39742ac52.

I check it on bscscan and ethscan, is it not a smart contract.

But logically, it should be the smart contract you wrote to do the check honey pot stuff and buy/sell stuff.

Am I in the right way?

**Comment by DexSniping** [comment]
> hi
> 
> I walk through the code and I found the swapper 0xaAA9c55FF5ce8e6431d84BE3cf9d0Ba39742ac52.
> 
> I check it on bscscan and ethscan, is it not a smart contract.
> 
> But logically, it should be the smart contract you wrote to do the check honey pot stuff and buy/sell stuff.
> 
> Am I in the right way?

Hey!

For BSC and ERC20 you don't need to have a smart contract to interact with the blockchain, that's why I'm using my own address ("0xaAA9c55FF5ce8e6431d84BE3cf9d0Ba39742ac52") to build my swapper object.

As you can see [here](https://github.com/DexSniping/DexSniping-BSC-ERC20-Telegram-Alerts/blob/045514c21e138566edfddf49a80dd4f25d505fa4/txns.py#L78): I'm checking if it's an Honeypot or not and [here](https://github.com/DexSniping/DexSniping-BSC-ERC20-Telegram-Alerts/blob/57e5b029f527bcae946cdea2d8a22f4a81f63f7b/sniper.py#L262) if the source token has min/max transaction taxes

> Hey bro! Nice work, I was asking if you can give me your telegram handle as i want to hire you for a task, thanks!

You can contact me here: https://t.me/dexsniping
